services:
  registry-sr:
    image: eurekaregistry 
    build: ./Eurekaregistry
    ports:
      - "8761:8761"
    networks:
      - wallet
    container_name: eurekaregistry1

  authentication-sr:
    image: springsecurity
    build: ./springsecuirtydemo
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-wallet:5432/securityservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "9097:9097"
    networks:
      - wallet
    depends_on:
      - registry-sr
      - api-gateway-sr
      - postgres-auth

  owner-sr:
    image: owner-image 
    build: ./owner
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-wallet:5432/wallet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "9096:9096"
    networks:
      - wallet
    depends_on:
      - registry-sr
      - api-gateway-sr

  api-gateway-sr:
    image: apigateway
    build: ./ApiGateway
    ports:
      - "8060:8060"
    networks:
      - wallet
    depends_on:
      - registry-sr

  postgres-auth:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: securityservice
    ports:
      - "5433:5432"  
    networks:
      - wallet

  postgres-wallet:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: wallet
    ports:
      - "5434:5432"  # Exposing different port for department DB
    networks:
      - wallet

networks:
  wallet:
    driver: bridge
